Update pipeline.yml

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -8,149 +8,147 @@ on:
       - '*'
 
 jobs:
+    
+  Lint-App:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+      - uses: actions/setup-node@v1
+      - name: linting for branch => ${{ github.ref }}
+      - run: |
+          echo "linting the app"
+          npm run lint || true # lint is currently failling
 
 
-    Lint-App:
-      runs-on: ubuntu-latest
-      steps:
-        - uses: actions/checkout@v2
-        - uses: actions/setup-node@v1
-        - name: linting for branch => ${{ github.ref }}
-        - run: |
-            echo "linting the app"
-            npm run lint || true # lint is currently failling
+  Test-on-GitHub:
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      max-parallel: 10
+      matrix:
+        os: [ubuntu-18.04, ubuntu-latest]
+        node-version: [12.x, 13.x]
+    steps:
+      - uses: actions/checkout@v1
+      - name: Using node version ${{ matrix.node-version }}
+        uses: actions/setup-node@v1
+        with:
+          node-version: ${{ matrix.node-version }}
 
+      - name: Prepare shell 
+        run: set -xeuo pipefail
 
+      - name: Prepare linux
+        if: startsWith(matrix.os, 'ubuntu')
+        run: |
+          sudo apt install encfs -y
+          npm ci
+          npm test
 
-    Test-on-GitHub:
-      runs-on: ubuntu-latest
-      strategy:
-        fail-fast: false
-        max-parallel: 10
-        matrix:
-          os: [ubuntu-18.04, ubuntu-latest]
-          node-version: [12.x, 13.x]
-        steps:
-          - uses: actions/checkout@v1
-          - name: Using node version ${{ matrix.node-version }}
-            uses: actions/setup-node@v1
-            with:
-              node-version: ${{ matrix.node-version }}
-              
-          - name: Prepare shell 
-            run: set -xeuo pipefail
-
-          - name: Prepare linux
-            if: startsWith(matrix.os, 'ubuntu')
-            run: |
-              sudo apt install encfs -y
-              npm ci
-              npm test
-              
-          - name: Prepare MAC
-            if: startsWith(matrix.os, 'macos')
-            run: |
-              /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
-              brew cask install osxfuse
-              brew install encfs
-              sudo security unlock-keychain -u
-              npm ci
-              # npm run make
+      - name: Prepare MAC
+        if: startsWith(matrix.os, 'macos')
+        run: |
+          /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+          brew cask install osxfuse
+          brew install encfs
+          sudo security unlock-keychain -u
+          npm ci
+          # npm run make
       
 
 
-    Test-on-Travis:
-      runs-on: ubuntu-latest
-      env:
-        BRANCH_FULL: ${{ github.ref }}
-        TRAVIS_TOKEN: ${{ secrets.TRAVIS_TOKEN }}
-      steps:
-        - run: echo ::set-env name=BRANCH::$(basename $BRANCH_FULL)
-        - run: echo "Building on branch $BRANCH and $GITHUB_REF_NAME"
-       
-        - uses: actions/checkout@v2
-        - uses: actions/setup-python@v1
-          with:
-            python-version: '3.x' # Semantic version range syntax or exact version of a Python version
-            architecture: 'x64' # Optional - x64 or x86, defaults to x64
+  Test-on-Travis:
+    runs-on: ubuntu-latest
+    env:
+      BRANCH_FULL: ${{ github.ref }}
+      TRAVIS_TOKEN: ${{ secrets.TRAVIS_TOKEN }}
+    steps:
+      - run: echo ::set-env name=BRANCH::$(basename $BRANCH_FULL)
+      - run: echo "Building on branch $BRANCH and $GITHUB_REF_NAME"
 
-        # - run: |
-        #     echo "Installing Travis "
-        #     set -eo pipefail
-        #     sudo apt install ruby-dev libffi-dev make gcc &&  sudo gem install travis
-        #     travis --version
-        #     travis login --pro --github-token ${{ secrets.TRAVIS_TOKEN }}
-        #     echo ::set-env name=TRAVIS_TOKEN_API::$(travis token --pro)
-          
-        - name: Testing on Travis for branch => ${{ github.ref }}
-          run: |
-            cd ./build
-            pip install -r requirements.txt
-            # python3 travis.py
+      - uses: actions/checkout@v2
+      - uses: actions/setup-python@v1
+        with:
+          python-version: '3.x' # Semantic version range syntax or exact version of a Python version
+          architecture: 'x64' # Optional - x64 or x86, defaults to x64
+
+      # - run: |
+      #     echo "Installing Travis "
+      #     set -eo pipefail
+      #     sudo apt install ruby-dev libffi-dev make gcc &&  sudo gem install travis
+      #     travis --version
+      #     travis login --pro --github-token ${{ secrets.TRAVIS_TOKEN }}
+      #     echo ::set-env name=TRAVIS_TOKEN_API::$(travis token --pro)
+
+      - name: Testing on Travis for branch => ${{ github.ref }}
+        run: |
+          cd ./build
+          pip install -r requirements.txt
+          # python3 travis.py
 
 
 
-    Build-Artifacts:
-      runs-on: ubuntu-latest
-      needs:  [Test-on-Travis, Lint-App]
-      steps:
-        - uses: actions/checkout@v2
-        - uses: actions/setup-node@v1
-        - name: linting for branch => ${{ github.ref }}
-        - run: |
-            echo "building artifacts"
-            npm ci
-            npm run make || true
+  Build-Artifacts:
+    runs-on: ubuntu-latest
+    needs:  [Test-on-Travis, Lint-App]
+    steps:
+      - uses: actions/checkout@v2
+      - uses: actions/setup-node@v1
+      - name: linting for branch => ${{ github.ref }}
+      - run: |
+          echo "building artifacts"
+          npm ci
+          npm run make || true
 
-        - name: uploading artifacts
-          run: |
-            echo "uploading artifacts"
-          # uses: actions/upload-artifact@v1
-          # with:
-          #   name: my id
-          #   path: actuall file
+      - name: uploading artifacts
+        run: |
+          echo "uploading artifacts"
+        # uses: actions/upload-artifact@v1
+        # with:
+        #   name: my id
+        #   path: actuall file
 
-    # distribute:
-      # if: ${{ startsWith(github.ref, 'features-' }}
-      # steps:
-      #   - name: download CLI image
-      #     uses: actions/download-artifact@v1
-      #     with:
-      #       name: raspbian-cli
+  # distribute:
+    # if: ${{ startsWith(github.ref, 'features-' }}
+    # steps:
+    #   - name: download CLI image
+    #     uses: actions/download-artifact@v1
+    #     with:
+    #       name: raspbian-cli
 
-      #   - name: download GUI image
-      #     uses: actions/download-artifact@v1
-      #     with:
-      #       name: raspbian-gui
+    #   - name: download GUI image
+    #     uses: actions/download-artifact@v1
+    #     with:
+    #       name: raspbian-gui
 
-      #   - name: create release
-      #     uses: actions/create-release@v1
-      #     id: create_release
-      #     env:
-      #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      #     with:
-      #         tag_name: ${{ github.run_number }}
-      #         release_name: Release ${{ github.run_number }}
-      #         draft: false
-      #         prerelease: false
-      #         body: |
-      #           Montly release of customised raspbians images lite (CLI only) and complete (with GUI)
-      #   - name: upload CLI image
-      #     uses: actions/upload-release-asset@v1
-      #     env:
-      #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      #     with:
-      #         upload_url: ${{ steps.create_release.outputs.upload_url }}
-      #         asset_path: ./raspbian-cli/raspbian-cli.img.zip
-      #         asset_name: raspbian-cli.img.zip
-      #         asset_content_type: application/zip
+    #   - name: create release
+    #     uses: actions/create-release@v1
+    #     id: create_release
+    #     env:
+    #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    #     with:
+    #         tag_name: ${{ github.run_number }}
+    #         release_name: Release ${{ github.run_number }}
+    #         draft: false
+    #         prerelease: false
+    #         body: |
+    #           Montly release of customised raspbians images lite (CLI only) and complete (with GUI)
+    #   - name: upload CLI image
+    #     uses: actions/upload-release-asset@v1
+    #     env:
+    #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    #     with:
+    #         upload_url: ${{ steps.create_release.outputs.upload_url }}
+    #         asset_path: ./raspbian-cli/raspbian-cli.img.zip
+    #         asset_name: raspbian-cli.img.zip
+    #         asset_content_type: application/zip
 
-      #   - name: upload GUI image
-      #     uses: actions/upload-release-asset@v1
-      #     env:
-      #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      #     with:
-      #         upload_url: ${{ steps.create_release.outputs.upload_url }}
-      #         asset_path: ./raspbian-gui/raspbian-gui.img.zip
-      #         asset_name: raspbian-gui.img.zip
-      #         asset_content_type: application/zip
+    #   - name: upload GUI image
+    #     uses: actions/upload-release-asset@v1
+    #     env:
+    #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    #     with:
+    #         upload_url: ${{ steps.create_release.outputs.upload_url }}
+    #         asset_path: ./raspbian-gui/raspbian-gui.img.zip
+    #         asset_name: raspbian-gui.img.zip
+    #         asset_content_type: application/zip
